import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"font-krypton antialiased"}>
        <main className="max-w-7xl mx-auto flex flex-col gap-4 justify-center items-center">
          <Navbar />
          <div className="max-w-6xl w-full flex flex-col gap-4 justify-center items-center">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
